- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.5.0
  hooks:
    - id: ruff
      files: ^packages/(core|backend)/
    - id: ruff-format
      files: ^packages/(core|backend)/

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v2.0.0
  hooks:
    - id: mypy
      files: ^packages/core/
      args: ["--explicit-package-bases", "--check-untyped-defs", "--ignore-missing-imports"]
      additional_dependencies:
        - types-requests